# File: docker-compose.yml (UNTUK PRODUKSI DENGAN COOLIFY)

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    restart: always
    labels:           
      - "coolify.expose.port=3000"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # [PERBAIKAN] Mengganti POSTGRAF menjadi POSTGRES
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: